export const dummyPlayerProps = {
  id: "0a5a9e810f06ed0adb33581b2163f143",
  sport_key: "basketball_nba",
  sport_title: "NBA",
  commence_time: "2025-01-02T00:10:00Z",
  home_team: "Washington Wizards",
  away_team: "Chicago Bulls",
  bookmakers: [
    {
      key: "fanduel",
      title: "FanDuel",
      markets: [
        {
          key: "player_assists",
          last_update: "2025-01-01T21:15:55Z",
          outcomes: [
            {
              name: "Over",
              description: "Bilal Coulibaly",
              price: 128,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Bilal Coulibaly",
              price: -158,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Jordan Poole",
              price: -140,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Jordan Poole",
              price: 114,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Josh Giddey",
              price: 106,
              point: 7.5,
            },
            {
              name: "Under",
              description: "Josh Giddey",
              price: -130,
              point: 7.5,
            },
            {
              name: "Over",
              description: "Zach LaVine",
              price: 122,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Zach LaVine",
              price: -150,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Coby White",
              price: 106,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Coby White",
              price: -130,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Nikola Vucevic",
              price: 132,
              point: 3.5,
            },
            {
              name: "Under",
              description: "Nikola Vucevic",
              price: -162,
              point: 3.5,
            },
          ],
        },
      ],
    },
    {
      key: "draftkings",
      title: "DraftKings",
      markets: [
        {
          key: "player_assists",
          last_update: "2025-01-01T21:16:43Z",
          outcomes: [
            {
              name: "Under",
              description: "Josh Giddey",
              price: -130,
              point: 7.5,
            },
            {
              name: "Over",
              description: "Josh Giddey",
              price: 100,
              point: 7.5,
            },
            {
              name: "Under",
              description: "Jordan Poole",
              price: 105,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Jordan Poole",
              price: -135,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Coby White",
              price: -105,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Coby White",
              price: -125,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Bilal Coulibaly",
              price: 120,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Bilal Coulibaly",
              price: -154,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Zach LaVine",
              price: 124,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Zach LaVine",
              price: -160,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Nikola Vucevic",
              price: -175,
              point: 3.5,
            },
            {
              name: "Over",
              description: "Nikola Vucevic",
              price: 135,
              point: 3.5,
            },
            {
              name: "Under",
              description: "Kyle Kuzma",
              price: -130,
              point: 2.5,
            },
            {
              name: "Over",
              description: "Kyle Kuzma",
              price: 100,
              point: 2.5,
            },
            {
              name: "Over",
              description: "Alex Sarr",
              price: 110,
              point: 2.5,
            },
            {
              name: "Under",
              description: "Alex Sarr",
              price: -140,
              point: 2.5,
            },
            {
              name: "Under",
              description: "Patrick Williams",
              price: 145,
              point: 1.5,
            },
            {
              name: "Over",
              description: "Patrick Williams",
              price: -188,
              point: 1.5,
            },
          ],
        },
      ],
    },
    {
      key: "betrivers",
      title: "BetRivers",
      markets: [
        {
          key: "player_assists",
          last_update: "2025-01-01T21:16:47Z",
          outcomes: [
            {
              name: "Over",
              description: "Nikola Vucevic",
              price: 123,
              point: 3.5,
            },
            {
              name: "Under",
              description: "Nikola Vucevic",
              price: -165,
              point: 3.5,
            },
            {
              name: "Over",
              description: "Coby White",
              price: 100,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Coby White",
              price: -132,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Josh Giddey",
              price: -105,
              point: 7.5,
            },
            {
              name: "Under",
              description: "Josh Giddey",
              price: -127,
              point: 7.5,
            },
            {
              name: "Over",
              description: "Zach LaVine",
              price: 123,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Zach LaVine",
              price: -165,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Bilal Coulibaly",
              price: 102,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Bilal Coulibaly",
              price: -134,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Jordan Poole",
              price: -132,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Jordan Poole",
              price: 100,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Kyle Kuzma",
              price: 108,
              point: 2.5,
            },
            {
              name: "Under",
              description: "Kyle Kuzma",
              price: -143,
              point: 2.5,
            },
          ],
        },
      ],
    },
    {
      key: "betmgm",
      title: "BetMGM",
      markets: [
        {
          key: "player_assists",
          last_update: "2025-01-01T21:16:03Z",
          outcomes: [
            {
              name: "Over",
              description: "Josh Giddey",
              price: 100,
              point: 7.5,
            },
            {
              name: "Under",
              description: "Josh Giddey",
              price: -130,
              point: 7.5,
            },
            {
              name: "Over",
              description: "Bilal Coulibaly",
              price: 105,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Bilal Coulibaly",
              price: -140,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Jordan Poole",
              price: -130,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Jordan Poole",
              price: 100,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Alex Sarr",
              price: 120,
              point: 2.5,
            },
            {
              name: "Under",
              description: "Alex Sarr",
              price: -160,
              point: 2.5,
            },
            {
              name: "Over",
              description: "Coby White",
              price: -105,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Coby White",
              price: -130,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Nikola Vucevic",
              price: 130,
              point: 3.5,
            },
            {
              name: "Under",
              description: "Nikola Vucevic",
              price: -175,
              point: 3.5,
            },
            {
              name: "Over",
              description: "Zach LaVine",
              price: 120,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Zach LaVine",
              price: -160,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Patrick Williams",
              price: -200,
              point: 1.5,
            },
            {
              name: "Under",
              description: "Patrick Williams",
              price: 150,
              point: 1.5,
            },
            {
              name: "Over",
              description: "Kyle Kuzma",
              price: 105,
              point: 2.5,
            },
            {
              name: "Under",
              description: "Kyle Kuzma",
              price: -140,
              point: 2.5,
            },
            {
              name: "Over",
              description: "Jalen Smith",
              price: -150,
              point: 0.5,
            },
            {
              name: "Under",
              description: "Jalen Smith",
              price: 110,
              point: 0.5,
            },
            {
              name: "Over",
              description: "Corey Kispert",
              price: 105,
              point: 1.5,
            },
            {
              name: "Under",
              description: "Corey Kispert",
              price: -145,
              point: 1.5,
            },
          ],
        },
      ],
    },
    {
      key: "bovada",
      title: "Bovada",
      markets: [
        {
          key: "player_assists",
          last_update: "2025-01-01T21:16:15Z",
          outcomes: [
            {
              name: "Over",
              description: "Bilal Coulibaly",
              price: 115,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Bilal Coulibaly",
              price: -150,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Coby White",
              price: 120,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Coby White",
              price: -160,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Jordan Poole",
              price: -145,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Jordan Poole",
              price: 110,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Josh Giddey",
              price: -105,
              point: 7.5,
            },
            {
              name: "Under",
              description: "Josh Giddey",
              price: -125,
              point: 7.5,
            },
            {
              name: "Over",
              description: "Nikola Vucevic",
              price: 130,
              point: 3.5,
            },
            {
              name: "Under",
              description: "Nikola Vucevic",
              price: -170,
              point: 3.5,
            },
            {
              name: "Over",
              description: "Zach LaVine",
              price: 130,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Zach LaVine",
              price: -170,
              point: 4.5,
            },
          ],
        },
      ],
    },
    {
      key: "betonlineag",
      title: "BetOnline.ag",
      markets: [
        {
          key: "player_assists",
          last_update: "2025-01-01T21:16:19Z",
          outcomes: [
            {
              name: "Over",
              description: "Coby White",
              price: 107,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Coby White",
              price: -139,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Zach LaVine",
              price: 120,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Zach LaVine",
              price: -156,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Nikola Vucevic",
              price: 134,
              point: 3.5,
            },
            {
              name: "Under",
              description: "Nikola Vucevic",
              price: -175,
              point: 3.5,
            },
            {
              name: "Under",
              description: "Jordan Poole",
              price: 107,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Jordan Poole",
              price: -139,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Josh Giddey",
              price: 100,
              point: 7.5,
            },
            {
              name: "Under",
              description: "Josh Giddey",
              price: -130,
              point: 7.5,
            },
            {
              name: "Over",
              description: "Bilal Coulibaly",
              price: 112,
              point: 4.5,
            },
            {
              name: "Under",
              description: "Bilal Coulibaly",
              price: -145,
              point: 4.5,
            },
            {
              name: "Over",
              description: "Alex Sarr",
              price: 117,
              point: 2.5,
            },
            {
              name: "Under",
              description: "Alex Sarr",
              price: -152,
              point: 2.5,
            },
            {
              name: "Over",
              description: "Kyle Kuzma",
              price: 103,
              point: 2.5,
            },
            {
              name: "Under",
              description: "Kyle Kuzma",
              price: -133,
              point: 2.5,
            },
            {
              name: "Over",
              description: "Patrick Williams",
              price: -192,
              point: 1.5,
            },
            {
              name: "Under",
              description: "Patrick Williams",
              price: 147,
              point: 1.5,
            },
          ],
        },
      ],
    },
  ],
};
